PREPROCESSING:
  DATASET: FaceForensics
  COMPRESSION: c23
  SPLIT: test
  # ROOT: C:/Users/tevca/Documents/College Work/LAA-Net/data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  ROOT: /content/drive/MyDrive/LAA-Net/LAA-Net-Temp/data/deepfake_cluster/datasets_df/FaceForensics++/c23
  # ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  # ROOT: /home/users/cataluns/LAA-net/data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  FAKETYPE: [Deepfakes, Face2Face, FaceSwap, Original, NeuralTextures]
  IMAGE_SUFFIX: png
  DATA_TYPE: frames
  LABEL: [fake, real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
  N_LANDMARKS: 81
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False
